// Code generated by protoc-gen-go.
// source: lldp.proto
// DO NOT EDIT!

/*
Package lldp is a generated protocol buffer package.

It is generated from these files:
	lldp.proto

It has these top-level messages:
	EmptyMessage
	Neighbor
	Interface
*/
package lldp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Neighbor struct {
	Portid          string `protobuf:"bytes,1,opt,name=portid" json:"portid,omitempty"`
	Portdescription string `protobuf:"bytes,2,opt,name=portdescription" json:"portdescription,omitempty"`
	Sysname         string `protobuf:"bytes,3,opt,name=sysname" json:"sysname,omitempty"`
	Sysdesc         string `protobuf:"bytes,4,opt,name=sysdesc" json:"sysdesc,omitempty"`
	Address         string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Vlan            string `protobuf:"bytes,6,opt,name=vlan" json:"vlan,omitempty"`
	Type            string `protobuf:"bytes,7,opt,name=type" json:"type,omitempty"`
}

func (m *Neighbor) Reset()                    { *m = Neighbor{} }
func (m *Neighbor) String() string            { return proto.CompactTextString(m) }
func (*Neighbor) ProtoMessage()               {}
func (*Neighbor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Interface struct {
	Index        int32  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Mtu          int32  `protobuf:"varint,2,opt,name=mtu" json:"mtu,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Hardwareaddr string `protobuf:"bytes,4,opt,name=hardwareaddr" json:"hardwareaddr,omitempty"`
	Flags        uint32 `protobuf:"varint,5,opt,name=flags" json:"flags,omitempty"`
}

func (m *Interface) Reset()                    { *m = Interface{} }
func (m *Interface) String() string            { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()               {}
func (*Interface) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "lldp.EmptyMessage")
	proto.RegisterType((*Neighbor)(nil), "lldp.Neighbor")
	proto.RegisterType((*Interface)(nil), "lldp.Interface")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Lldp service

type LldpClient interface {
	ListInterfaces(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (Lldp_ListInterfacesClient, error)
	GetInterfaceDetails(ctx context.Context, in *Interface, opts ...grpc.CallOption) (*Interface, error)
	ListInterfaceNeighbors(ctx context.Context, in *Interface, opts ...grpc.CallOption) (Lldp_ListInterfaceNeighborsClient, error)
	ListNeighbors(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (Lldp_ListNeighborsClient, error)
}

type lldpClient struct {
	cc *grpc.ClientConn
}

func NewLldpClient(cc *grpc.ClientConn) LldpClient {
	return &lldpClient{cc}
}

func (c *lldpClient) ListInterfaces(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (Lldp_ListInterfacesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lldp_serviceDesc.Streams[0], c.cc, "/lldp.Lldp/ListInterfaces", opts...)
	if err != nil {
		return nil, err
	}
	x := &lldpListInterfacesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lldp_ListInterfacesClient interface {
	Recv() (*Interface, error)
	grpc.ClientStream
}

type lldpListInterfacesClient struct {
	grpc.ClientStream
}

func (x *lldpListInterfacesClient) Recv() (*Interface, error) {
	m := new(Interface)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lldpClient) GetInterfaceDetails(ctx context.Context, in *Interface, opts ...grpc.CallOption) (*Interface, error) {
	out := new(Interface)
	err := grpc.Invoke(ctx, "/lldp.Lldp/GetInterfaceDetails", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lldpClient) ListInterfaceNeighbors(ctx context.Context, in *Interface, opts ...grpc.CallOption) (Lldp_ListInterfaceNeighborsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lldp_serviceDesc.Streams[1], c.cc, "/lldp.Lldp/ListInterfaceNeighbors", opts...)
	if err != nil {
		return nil, err
	}
	x := &lldpListInterfaceNeighborsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lldp_ListInterfaceNeighborsClient interface {
	Recv() (*Neighbor, error)
	grpc.ClientStream
}

type lldpListInterfaceNeighborsClient struct {
	grpc.ClientStream
}

func (x *lldpListInterfaceNeighborsClient) Recv() (*Neighbor, error) {
	m := new(Neighbor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lldpClient) ListNeighbors(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (Lldp_ListNeighborsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lldp_serviceDesc.Streams[2], c.cc, "/lldp.Lldp/ListNeighbors", opts...)
	if err != nil {
		return nil, err
	}
	x := &lldpListNeighborsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lldp_ListNeighborsClient interface {
	Recv() (*Neighbor, error)
	grpc.ClientStream
}

type lldpListNeighborsClient struct {
	grpc.ClientStream
}

func (x *lldpListNeighborsClient) Recv() (*Neighbor, error) {
	m := new(Neighbor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Lldp service

type LldpServer interface {
	ListInterfaces(*EmptyMessage, Lldp_ListInterfacesServer) error
	GetInterfaceDetails(context.Context, *Interface) (*Interface, error)
	ListInterfaceNeighbors(*Interface, Lldp_ListInterfaceNeighborsServer) error
	ListNeighbors(*EmptyMessage, Lldp_ListNeighborsServer) error
}

func RegisterLldpServer(s *grpc.Server, srv LldpServer) {
	s.RegisterService(&_Lldp_serviceDesc, srv)
}

func _Lldp_ListInterfaces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LldpServer).ListInterfaces(m, &lldpListInterfacesServer{stream})
}

type Lldp_ListInterfacesServer interface {
	Send(*Interface) error
	grpc.ServerStream
}

type lldpListInterfacesServer struct {
	grpc.ServerStream
}

func (x *lldpListInterfacesServer) Send(m *Interface) error {
	return x.ServerStream.SendMsg(m)
}

func _Lldp_GetInterfaceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Interface)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LldpServer).GetInterfaceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lldp.Lldp/GetInterfaceDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LldpServer).GetInterfaceDetails(ctx, req.(*Interface))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lldp_ListInterfaceNeighbors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Interface)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LldpServer).ListInterfaceNeighbors(m, &lldpListInterfaceNeighborsServer{stream})
}

type Lldp_ListInterfaceNeighborsServer interface {
	Send(*Neighbor) error
	grpc.ServerStream
}

type lldpListInterfaceNeighborsServer struct {
	grpc.ServerStream
}

func (x *lldpListInterfaceNeighborsServer) Send(m *Neighbor) error {
	return x.ServerStream.SendMsg(m)
}

func _Lldp_ListNeighbors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LldpServer).ListNeighbors(m, &lldpListNeighborsServer{stream})
}

type Lldp_ListNeighborsServer interface {
	Send(*Neighbor) error
	grpc.ServerStream
}

type lldpListNeighborsServer struct {
	grpc.ServerStream
}

func (x *lldpListNeighborsServer) Send(m *Neighbor) error {
	return x.ServerStream.SendMsg(m)
}

var _Lldp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lldp.Lldp",
	HandlerType: (*LldpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInterfaceDetails",
			Handler:    _Lldp_GetInterfaceDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListInterfaces",
			Handler:       _Lldp_ListInterfaces_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListInterfaceNeighbors",
			Handler:       _Lldp_ListInterfaceNeighbors_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListNeighbors",
			Handler:       _Lldp_ListNeighbors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("lldp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0xfc, 0xf2, 0x35, 0x69, 0xe9, 0xaa, 0x3f, 0x68, 0x41, 0x95, 0xc5, 0x09, 0xe5, 0xd4, 0x53,
	0x85, 0xe0, 0x80, 0x7a, 0xe0, 0x06, 0x42, 0x48, 0x85, 0x43, 0xde, 0xc0, 0xad, 0xb7, 0xad, 0xa5,
	0x34, 0xb1, 0x6c, 0xf3, 0xd3, 0x23, 0xaf, 0xc6, 0x33, 0xf1, 0x00, 0xc8, 0x76, 0x9a, 0xfe, 0x28,
	0xb7, 0x99, 0xd9, 0x19, 0x7b, 0x92, 0x35, 0x40, 0x9e, 0x0b, 0x35, 0x51, 0xba, 0xb4, 0x25, 0xc6,
	0x0e, 0xa7, 0x03, 0xe8, 0x3d, 0x6d, 0x94, 0xdd, 0xbe, 0x92, 0x31, 0x7c, 0x45, 0xe9, 0x4f, 0x04,
	0x67, 0x6f, 0x24, 0x57, 0xeb, 0x79, 0xa9, 0x71, 0x04, 0x6d, 0x55, 0x6a, 0x2b, 0x05, 0x8b, 0xae,
	0xa3, 0x71, 0x37, 0xab, 0x18, 0x8e, 0x61, 0xe8, 0x90, 0x20, 0xb3, 0xd0, 0x52, 0x59, 0x59, 0x16,
	0xec, 0xbf, 0x37, 0x9c, 0xca, 0xc8, 0xa0, 0x63, 0xb6, 0xa6, 0xe0, 0x1b, 0x62, 0x2d, 0xef, 0xd8,
	0xd1, 0x6a, 0xe2, 0xbc, 0x2c, 0xae, 0x27, 0x8e, 0xba, 0x09, 0x17, 0x42, 0x93, 0x31, 0x2c, 0x09,
	0x93, 0x8a, 0x22, 0x42, 0xfc, 0x91, 0xf3, 0x82, 0xb5, 0xbd, 0xec, 0xb1, 0xd3, 0xec, 0x56, 0x11,
	0xeb, 0x04, 0xcd, 0xe1, 0xf4, 0x3b, 0x82, 0xee, 0x4b, 0x61, 0x49, 0x2f, 0xf9, 0x82, 0xf0, 0x12,
	0x12, 0x59, 0x08, 0xfa, 0xf2, 0x1f, 0x91, 0x64, 0x81, 0xe0, 0x39, 0xb4, 0x36, 0xf6, 0xdd, 0xf7,
	0x4e, 0x32, 0x07, 0xdd, 0x49, 0x07, 0x45, 0x3d, 0xc6, 0x14, 0x7a, 0x6b, 0xae, 0xc5, 0x27, 0xd7,
	0xe4, 0x4a, 0x54, 0x55, 0x8f, 0x34, 0x77, 0xfe, 0x32, 0xe7, 0xab, 0xd0, 0xb6, 0x9f, 0x05, 0x72,
	0xfb, 0x1b, 0x41, 0x3c, 0xcb, 0x85, 0xc2, 0x29, 0x0c, 0x66, 0xd2, 0xd8, 0xba, 0x8f, 0x41, 0x9c,
	0xf8, 0x35, 0x1c, 0xfe, 0xf7, 0xab, 0x61, 0xd0, 0x6a, 0x57, 0xfa, 0xef, 0x26, 0xc2, 0x29, 0x5c,
	0x3c, 0xd3, 0x3e, 0xf9, 0x48, 0x96, 0xcb, 0xdc, 0xe0, 0xa9, 0xb7, 0x21, 0x8c, 0x0f, 0x30, 0x3a,
	0xba, 0x75, 0xb7, 0xd3, 0x86, 0xf4, 0x20, 0x08, 0x3b, 0x87, 0xbf, 0xf9, 0x1e, 0xfa, 0x2e, 0xbe,
	0x4f, 0x35, 0x75, 0x6e, 0x08, 0xce, 0xdb, 0xfe, 0x71, 0xdd, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x15, 0x5e, 0x19, 0x0d, 0x6a, 0x02, 0x00, 0x00,
}
