sudo: required
services:
  - docker
language: go
go:
  - 1.7
before_install:
  - echo -e "machine github.com\n  login $GITHUB_USER\n  password $GITHUB_PASS" >> ~/.netrc
script:
  - make 
after_success:
  - make coveralls
