sudo: required
services:
- docker
language: go
go:
- 1.7
before_install:
- echo -e "machine github.com\n  login $GITHUB_USER\n  password $GITHUB_PASS" >> ~/.netrc
script:
- make
after_success:
- make coveralls
notifications:
  slack:
    secure: qc4QO0mvbHY9d1t9lIjpi8wK2mKpV698CGYOMWdEfdv+rj8gbuCPX/BMJ/55YIy+n1V9RSs+4WnWDv/RhcOF2A6vQUDycqBfU8li94s7pMNPu8gsNEyUUDG8Y+ya9ooGjW6gRFwFR7tiF0x45VrkiWXmLnEe/ka7v9Vu3pfCmV6mqF/13Dn9iZJHXvMmBGFiNQFjZfsBjO0rlcEkrYTVo9wBfZHYVbbVWOUYyl2F8GlXmqWCckEQkAPRqu2GijwI+NhyaIfPrW7kuwGforjbLpxgmRgER8F+9w6XGSANlWB0pzOfGAuCPKlGsfQTVsuSaEd2/eqVTcKGZJjy3mjUo3vBpifkoIbBiartInFRqSg+n2zmoF3FAPeCrMnX0YqacNrWrf/YmJuQzIVEhnmQiCGCVB0d9B9vzYpaXqWy8BQaBl4Wnwikmw1aNE5XXGfKUBhKj7dBczNTAu7KmgsAo67Og/CzxR7vGp+COjs3Ns5Ly+ec97slbQcejx0erpTLzzzanrcCe4qMny9FMVYQvxI4myLE3qpRYHWRHzlblkPZG/n8oplKD4vMYNbFDm2rNv9Y7v8naLMCun8Ux7vt7vg+msykuXj9T+kxCzw1F7V9E2RN5utEDGL+notR5a7bwEBPbIFU99ZjLemJZ54KhVXs23Sk8VfJd0cLHRo7j6Q=
env:
  global:
  - secure: RWDefObXIl3AMKVlXtUDWEDx/j3qHxHAmJ6/t/P2ak2FKx0gtEpyDe6gOY4x+svVOMjVe1k6BfZcfDfZx80UbFirZhDbCj2dU0j8sgxhbnprVZ6nFoM6tcJWu2dGYJVwnaGrNE+m/dA3Zl0fp7HeMi+p4jaVZSi/BL96bSTdygjAQEO9cuqv7w0cA33hBSi8HGSsZ67cEhOFqlEL70alz051L85FFMn2MmKaPPylQ5lm6If/CF14hqW18/Ci0/XBRUp5+yDq4ohzw/+A62Yt/RXJUzg4XkMPbM7hfbPcgEUzurwmv0fn4h5F0vaek2n5GTkS11ArsjDVudE3Iti45FwKAIUNDa3wxIF1wH/qW9VRr10E6y6Nz1RhEB+NV4zpedcUMnHwMOAQ8OP93WkfHuVGV4PZ3g1T1vmQ3+Hf8qUGXp2ljngFqpQF0ksvnXIm9pByFezJbMrsM2ApGvL9yngrAp4rOEQicQmI6YTuSXEoSufTf4ordwbRxyRGb0kZmPZi6cj2cym3UKA/9QzF4GBNSkOftbOP/T68DUI5r64zpDYmqlaB+0CmscS6zNxWKmQdCcfKhhOqobUryE7IK7U8gCWFg+ZGWyRL34CcoqmY/bqsHkbEWsTxSMdjaRktg8BhfDVlvMHqcIOO8OxgOXNRuaXISPlsXUFg0l8wi1E=
  - secure: B6erGGsuUOITyNWTr5p57ymQULpgxIDMRfz5m/RgzYrWcQstqrihb5STC/XMv8fsfvj2hAQXtfZ9bj9Jms5XJe4tyCCRW47gpfP/opfAs2zwEMLXumm+2Q+JENvHWpg437Azf/KU4ERsaa8bLdYpZdeOguSoxc6tt+4OsDZfcgD+/2iCV03DWEyirp3XOR8DK3pn2/BDKU7f6PAGW1fGnHOSD5RwSYR7nq2SE/lN/+RT3h6SKmITTGKbnS246wxzOtMDhweft9q23JBTzwjYYKGsq0mdBtpprXYZvcykqbfPBGba2KjBIK7qNloGFGoFGKXvkAPExzPKRjQ+/iiBN/Scii6yryhCkO2mmcNSbKYtxx6WfBGH3aeKxevGWgI1fMRKsrdBQPkxd98ebZcDhsVoiGUJqBm5qcUwPCQPo5ZoYFJ6xxxzbrRh4c2CUY+dUazJDt6K8nfWE2a7ohM55BrOl3D0fpNCxZCghiOnGASnnEeOWiTgfb3zosWSq9DPLlFhp3TP0iLwiM45vdCbcc6LywTrBseIKoPhfR7L8LdRo95apHZjZm+4z/Bu+UgKpeyNeSWq85izcgwLys3X975S0b79UEufLUBfQqHaa2yYzU5P6mMlqTZonk/y++6zj8miPV03r5uUsTmnngJOa1//iQaOXUV8KUNxaJ1ErdA=
